jobs:
  build:
    name: Check Frozen Imports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dhall-lang/setup-dhall@v4.2.0
      - name: dhall freeze
        run: dhall freeze --all --inplace ./package.dhall
        
name: Test
on:
  push: {}
